name: main
on: 
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Yarn install
        run: yarn install

      - name: Build Code
        run: yarn build

      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: test-gh-pages
          build_dir: dist
          fqdn: gov.evolution.land
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

